services:
  app:
    build:
      context: .
      target: prod
      args:
        WITH_SQLITE: "0"     # set to "1" only if you want SQLite compiled in
    image: tiny-tasks:latest
    environment:
      PORT: "3000"           # container listens on 3000
      STORAGE: "json"        # memory | json | sqlite
      TASKS_JSON_PATH: "/app/data/tasks.json"
      # TASKS_SQLITE_PATH: "/app/data/tasks.db"   # if STORAGE=sqlite
      # LOG_JSON: "1"                             # optional structured logs
    volumes:
      - tasks_data:/app/data
    ports:
      - "3001:3000"          # host 3001 → container 3000
    restart: unless-stopped

volumes:
  tasks_data: {}
