services:
  app:
    build:
      context: .
      target: prod
      args:
        WITH_SQLITE: "1"         # build image with better-sqlite3
    image: tiny-tasks:latest
    environment:
      PORT: "3000"
      STORAGE: "sqlite"          # use SQLite storage
      TASKS_SQLITE_PATH: "/app/data/tasks.db"
    volumes:
      - tasks_data_sqlite:/app/data
    ports:
      - "3001:3000"              # publish host TCP 3001 → container TCP 3000
    restart: unless-stopped

volumes:
  tasks_data_sqlite: {}
