name: CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['20.x', '22.x']  # matches package.json "engines": ">=20 <23"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install (ci)
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Unit tests
        run: npm test

  docker-build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (no SQLite)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          target: prod
          tags: tiny-tasks:ci-nonsqlite
          build-args: |
            WITH_SQLITE=0

      - name: Build image (with SQLite)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          target: prod
          tags: tiny-tasks:ci-sqlite
          build-args: |
            WITH_SQLITE=1
