name: OpenAPI Lint
on:
  push:
  pull_request:

jobs:
  lint-openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Lint openapi.yaml with Redocly v2.0.4
        run: npx @redocly/cli@2.0.4 lint openapi.yaml
