name: lint-openapi

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - name: Lint openapi.yaml with Redocly v2.0.4
        run: npx @redocly/cli@2.0.4 lint openapi.yaml
