name: lint-openapi

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - name: Install (best-effort)
        run: npm ci || true
      - name: Lint OpenAPI
        run: npx --yes @redocly/cli@latest lint openapi.yaml
