name: Release

on:
  push:
    tags:
      - 'v*'     # e.g. v1.2.3

permissions:
  contents: read
  packages: write   # push to GHCR

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata (sqlite)
        id: meta_sqlite
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}

      - name: Build & push (sqlite; multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          target: prod
          platforms: linux/amd64,linux/arm64
          build-args: |
            WITH_SQLITE=1
          tags: ${{ steps.meta_sqlite.outputs.tags }}
          labels: ${{ steps.meta_sqlite.outputs.labels }}

      - name: Docker metadata (nosqlite)
        id: meta_nosqlite
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}-nosqlite
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}

      - name: Build & push (no SQLite; multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          target: prod
          platforms: linux/amd64,linux/arm64
          build-args: |
            WITH_SQLITE=0
          tags: ${{ steps.meta_nosqlite.outputs.tags }}
          labels: ${{ steps.meta_nosqlite.outputs.labels }}
